# fly.toml app configuration file generated for loopstream on 2026-07-26T23:57:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loopstream'
primary_region = 'ams'
swap_size_mb = 256

[build]

[env]
  MAX_HOURS = '6'
  REFRESH = '0'
  RTMP_URL = 'rtmp://live.restream.io/live'
  STALL_TIMEOUT = '45'
  VB = '1800k'
  VIDEO_URL = 'https://files.catbox.moe/example.mp4'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'always'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
